In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [4]:
score = np.loadtxt('../data-01-test-score.csv', delimiter=',', dtype=np.float32)
print(score)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [5]:
x = np.array(score[:, 0:-1])
y = np.array(score[:, [-1]])
print(x)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]


In [6]:
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=[3,]))
model.add(tf.keras.layers.Dense(units=1))

In [7]:
model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-6))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 4 (16.00 Byte)
Trainable params: 4 (16.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [8]:
model.fit(x, y, epochs=2000)

Epoch 1/2000
1/1 [==============================] - 1s 608ms/step - loss: 4788.7373
Epoch 2/2000
1/1 [==============================] - 0s 8ms/step - loss: 4421.5225
Epoch 3/2000
1/1 [==============================] - 0s 7ms/step - loss: 4082.5291
Epoch 4/2000
1/1 [==============================] - 0s 7ms/step - loss: 3769.5881
Epoch 5/2000
1/1 [==============================] - 0s 9ms/step - loss: 3480.6975
Epoch 6/2000
1/1 [==============================] - 0s 7ms/step - loss: 3214.0098
Epoch 7/2000
1/1 [==============================] - 0s 10ms/step - loss: 2967.8169
Epoch 8/2000
1/1 [==============================] - 0s 9ms/step - loss: 2740.5459
Epoch 9/2000
1/1 [==============================] - 0s 7ms/step - loss: 2530.7417
Epoch 10/2000
1/1 [==============================] - 0s 7ms/step - loss: 2337.0610
Epoch 11/2000
1/1 [==============================] - 0s 9ms/step - loss: 2158.2649
Epoch 12/2000
1/1 [==============================] - 0s 8ms/step - loss: 1993.2100
Epoch 13/2

In [9]:
y_predict = model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

1/1 [==============================] - 0s 120ms/step
[[178.35092]]


In [10]:
print("Your score will be ", model.predict(np.array([[100, 70, 101]])))

1/1 [==============================] - 0s 65ms/step
Your score will be  [[177.67459]]
