In [58]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [59]:
score = np.loadtxt('../data-01-test-score.csv', delimiter=',', dtype=np.float32)
print(score)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [60]:
x = np.array(score[:, 0:-1])
y = np.array(score[:, [-1]])
print(x)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]


In [69]:
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=[3,]))
model.add(tf.keras.layers.Dense(units=1))

In [70]:
model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(learning_rate=1e-6))
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_8 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4 (16.00 B)

 Trainable params: 4 (16.00 B)

 Non-trainable params: 0 (0.00 B)

In [73]:
model.fit(x, y, epochs=2000)

Epoch 1/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 8.9586
Epoch 2/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 8.9583
Epoch 3/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 8.9580
Epoch 4/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 8.9578
Epoch 5/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 8.9576
Epoch 6/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 8.9573
Epoch 7/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 8.9570
Epoch 8/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 8.9568
Epoch 9/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 8.9566
Epoch 10/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 8.9563
Epoch 11/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 8.9561
Epoch 12/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 8.9558
Epoch 13/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 8.9556
Epoch 14/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 8.9553
Epoch 15/2000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 8.9551
Epoc

In [72]:
y_predict = model.predict(np.array([[72., 93., 90.]]))
print(y_predict)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[178.95544]]


In [77]:
print("Your score will be ", model.predict(np.array([[100, 70, 101]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
Your score will be  [[178.80847]]
